# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: "3.7"

volumes:
  raft1.libBadge.com:
  raft2.libBadge.com:
  peer0.library.libBadge.com:
  peer1.library.libBadge.com:
  peer0.student.libBadge.com:
  peer1.student.libBadge.com:

networks:
  test:

services:
  raft1.libBadge.com:
    container_name: raft1.libBadge.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/raft1.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/raft1.genesis.block
      - ../organizations/ordererOrganizations/libBadge.com/orderers/raft1.libBadge.com/msp:/var/hyperledger/orderer/msp
      - ../organizations/ordererOrganizations/libBadge.com/orderers/raft1.libBadge.com/tls/:/var/hyperledger/orderer/tls
      - raft1.libBadge.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      - test

  raft2.libBadge.com:
    container_name: raft2.libBadge.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=8050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/raft2.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/raft2.genesis.block
      - ../organizations/ordererOrganizations/libBadge.com/orderers/raft2.libBadge.com/msp:/var/hyperledger/orderer/msp
      - ../organizations/ordererOrganizations/libBadge.com/orderers/raft2.libBadge.com/tls/:/var/hyperledger/orderer/tls
      - raft2.libBadge.com:/var/hyperledger/production/orderer
    ports:
      - 8050:8050
    networks:
      - test

  peer0.library.libBadge.com:
    container_name: peer0.library.libBadge.com
    image: hyperledger/fabric-peer:latest
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.library.libBadge.com
      - CORE_PEER_ADDRESS=peer0.library.libBadge.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.library.libBadge.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.library.libBadge.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.library.libBadge.com:7051
      - CORE_PEER_LOCALMSPID=LibraryMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../organizations/peerOrganizations/library.libBadge.com/peers/peer0.library.libBadge.com/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/library.libBadge.com/peers/peer0.library.libBadge.com/tls:/etc/hyperledger/fabric/tls
      - peer0.library.libBadge.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    depends_on:
      - raft1.libBadge.com
      - raft2.libBadge.com
    ports:
      - 7051:7051
    networks:
      - test

  peer1.library.libBadge.com:
    container_name: peer1.library.libBadge.com
    image: hyperledger/fabric-peer:latest
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer1.library.libBadge.com
      - CORE_PEER_ADDRESS=peer1.library.libBadge.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.library.libBadge.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.library.libBadge.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.library.libBadge.com:8051
      - CORE_PEER_LOCALMSPID=LibraryMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../organizations/peerOrganizations/library.libBadge.com/peers/peer1.library.libBadge.com/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/library.libBadge.com/peers/peer1.library.libBadge.com/tls:/etc/hyperledger/fabric/tls
      - peer1.library.libBadge.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    depends_on:
      - raft1.libBadge.com
      - raft2.libBadge.com
    ports:
      - 8051:8051
    networks:
      - test

  peer0.student.libBadge.com:
    container_name: peer0.student.libBadge.com
    image: hyperledger/fabric-peer:latest
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.student.libBadge.com
      - CORE_PEER_ADDRESS=peer0.student.libBadge.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.student.libBadge.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.student.libBadge.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.student.libBadge.com:9051
      - CORE_PEER_LOCALMSPID=StudentMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../organizations/peerOrganizations/student.libBadge.com/peers/peer0.student.libBadge.com/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/student.libBadge.com/peers/peer0.student.libBadge.com/tls:/etc/hyperledger/fabric/tls
      - peer0.student.libBadge.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    depends_on:
      - raft1.libBadge.com
      - raft2.libBadge.com
    ports:
      - 9051:9051
    networks:
      - test

  peer1.student.libBadge.com:
    container_name: peer1.student.libBadge.com
    image: hyperledger/fabric-peer:latest
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer1.student.libBadge.com
      - CORE_PEER_ADDRESS=peer1.student.libBadge.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.student.libBadge.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.student.libBadge.com:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.student.libBadge.com:10051
      - CORE_PEER_LOCALMSPID=StudentMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../organizations/peerOrganizations/student.libBadge.com/peers/peer1.student.libBadge.com/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/student.libBadge.com/peers/peer1.student.libBadge.com/tls:/etc/hyperledger/fabric/tls
      - peer1.student.libBadge.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    depends_on:
      - raft1.libBadge.com
      - raft2.libBadge.com
    ports:
      - 10051:10051
    networks:
      - test
