OrdererOrgs:
  - Name: Orderer
    Domain: libBadge.com
    Specs:
      - Hostname: orderer1
      - Hostname: orderer2
      - Hostname: orderer3

PeerOrgs:
  - Name: Library
    Domain: library.libBadge.com
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Student
    Domain: student.libBadge.com
    Template:
      Count: 2
    Users:
      Count: 1
